### PR TITLE
Update GHA configuration

### PR DESCRIPTION
**Pull request by CAMOBAP**
As title. 

 _Generated by Cimas_.

### CODE REVIEW

**Comment by CAMOBAP** [comment]
Looks like `secrets.METANORMA_CI_PAT_TOKEN` inaccessible, afaik it defined on the organization level, @ronaldtse  could you please check maybe there is some missconfiguration

**Comment by CAMOBAP** [comment]
Looks like `secrets.METANORMA_CI_PAT_TOKEN` inaccessible, afaik it defined on the organization level, @ronaldtse  could you please check maybe there is some missconfiguration

**Comment by ronaldtse** [comment]
@CAMOBAP yes you're right! I've enabled for this repo.

**Comment by ronaldtse** [comment]
Actually @CAMOBAP the secret is defined in org and available for all public repositories...

**Comment by ronaldtse** [comment]
What's the error?

**Comment by CAMOBAP** [comment]
@ronaldtse 

```
Error: Error setting status:
Not Found
```

https://github.com/metanorma/isoics/pull/16/checks?check_run_id=1419194899

For most of repos, it works, but for some, it doesn't:
 - https://github.com/metanorma/csa-ccm-tools/pull/28
 - https://github.com/metanorma/metanorma-bipm/pull/71
 - https://github.com/metanorma/metanorma-ietf/pull/115
 - https://github.com/metanorma/metanorma-gb/pull/145
 - https://github.com/metanorma/isoics/pull/16

**Comment by CAMOBAP** [comment]
@ronaldtse could you please check the message above?

**Comment by ronaldtse** [comment]
I found out the issue -- this repo didn't have the metanorma/ci group enabled with write access. Fixed now.

**Pull request merged**
